
services:
  llm-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/app/.cache/transformers
      - HF_HOME=/app/.cache/huggingface
    volumes:
      - model-cache:/app/.cache
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  model-cache:
    driver: local
